Started on 03/22/16 21:29:18
    TestAnotherThing.test1_Success1 ... Ok
    TestAnotherThing.test1_Success2 ... Ok
    TestAnotherThing.test3_Fail1 ... FAIL
test/test_with_err_fail_pass.lua:49: expected: 0, actual: 2
    TestAnotherThing.test3_Fail2 ... FAIL
test/test_with_err_fail_pass.lua:53: expected: 0, actual: 3
    TestSomething.test1_Success1 ... Ok
    TestSomething.test1_Success2 ... Ok
    TestSomething.test2_Fail1 ... FAIL
test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
    TestSomething.test2_Fail2 ... FAIL
test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
    testFuncFail1 ... FAIL
test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
    testFuncSuccess1 ... Ok
=========================================================
Failed tests:
-------------
1) TestAnotherThing.test3_Fail1
test/test_with_err_fail_pass.lua:49: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.lua:49: in function 'TestAnotherThing.test3_Fail1'

2) TestAnotherThing.test3_Fail2
test/test_with_err_fail_pass.lua:53: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:53: in function 'TestAnotherThing.test3_Fail2'

3) TestSomething.test2_Fail1
test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.lua:15: in function 'TestSomething.test2_Fail1'

4) TestSomething.test2_Fail2
test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:19: in function 'TestSomething.test2_Fail2'

5) testFuncFail1
test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:62: in function 'testFuncFail1'

Ran 10 tests in 0.001 seconds, 5 successes, 5 failures, 5 non-selected
